### ISSUE TITLE
How to render a 360 view video

### ISSUE THREAD

**Issue by thuanz123** [chinhsuanwu/dreamfusionacc#1]
Can I ask how to render 360 view like the one in README?

**Comment by chinhsuanwu** [comment]
Sure. You can get it by simply running this command in the output `rgb` folder
```bash
convert -delay 7 -loop 0 $(ls -1 *.png | sort -V) ../rgb.gif
```
Make sure you install `imagemagick` in advance.

**Comment by thuanz123** [comment]
Thanks, one more question: it seems that the object appears too close to the camera, what hyper-parameter I need to change to make the object far away. Like the peacock is too close

**Comment by chinhsuanwu** [comment]
You can change the radius of poses at this line

https://github.com/chinhsuanwu/dreamfusionacc/blob/5293d65c80b3a26b63c624b7c47edb03f43e5299/dataset/dreamfusion.py#L107C18-L107C18

It doesn't work in a too configurable way right now but will add it to the config later
